# Generated by Django 4.2.3 on 2023-07-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='store/img')),
            ],
        ),
    ]
